// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsLdH6ZGdHir5ETSUSQhV_7kMi0C2sjLg',
    appId: '1:617404245606:web:6e5d5cfdd0364da1aeefa7',
    messagingSenderId: '617404245606',
    projectId: 'chit-chat-70bb1',
    authDomain: 'chit-chat-70bb1.firebaseapp.com',
    storageBucket: 'chit-chat-70bb1.appspot.com',
    measurementId: 'G-K1CEKM65ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBim-FHpkvGp7laBvq60ehYx4vFK6UrmPc',
    appId: '1:617404245606:android:768115a3319e1632aeefa7',
    messagingSenderId: '617404245606',
    projectId: 'chit-chat-70bb1',
    storageBucket: 'chit-chat-70bb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1BT7ttefERE1f53JCQOSrr3oKfjgwTHU',
    appId: '1:617404245606:ios:f24495a030de1032aeefa7',
    messagingSenderId: '617404245606',
    projectId: 'chit-chat-70bb1',
    storageBucket: 'chit-chat-70bb1.appspot.com',
    iosBundleId: 'com.example.chitChat',
  );
}
